name: Promote Release

on:
  push:
    branches:
      - "release_*"

permissions:
  contents: read
  pull-requests: write

jobs:
  promote:
    uses: ShaikhWaleed-1994/shared_pr_workflow/.github/workflows/promote-reusable.yml@main
